# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55c3995889641005c24ba4d11f386a57bb0115a19eb1bba512b25b36e3b14acb634254cc9cededa3f3ee8863d8dd0f5d34ff76a14ea7e3985183310ecc82485c

test:
  secret_key_base: 67c6baf4259a5e59e99e02e6f6b2adea005c06280be5da55695572f069be7e8dfa49fcf2f8653de8d44855814cc0abcd9c467b69aaab218e0bc8bcb29d0aa423

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
